# Generated by Django 2.1.4 on 2018-12-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('teamName', models.CharField(max_length=50)),
                ('roomName', models.CharField(max_length=50)),
                ('writerName', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
                ('keyword', models.CharField(max_length=50)),
                ('createdAt', models.CharField(max_length=50)),
            ],
        ),
    ]
