# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='lat_name',
            new_name='last_name',
        ),
    ]
