# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181226_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('teamName', models.CharField(max_length=30)),
                ('roomName', models.CharField(max_length=30)),
                ('writerName', models.CharField(max_length=30)),
                ('writerEmail', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=1000)),
                ('keyword', models.CharField(max_length=30)),
                ('createAt', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
