# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181227_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
