# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181227_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='createdAt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='keyword',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='roomName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='teamName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='token',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='writerEmail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='writerName',
            field=models.CharField(max_length=50),
        ),
    ]
